# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 13:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drilling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drilling', models.CharField(max_length=200, verbose_name='drilling:')),
                ('drilling_no', models.IntegerField(default=0, verbose_name='ｼｬﾝｸ部刻印No')),
                ('drilling_exchange', models.CharField(max_length=200, verbose_name='drilling_exchange:')),
                ('StartEnd', models.CharField(max_length=200, verbose_name='StartEnd:')),
                ('Date', models.DateField(default=datetime.datetime(2017, 10, 11, 13, 35, 12, 656090), verbose_name='日付選択')),
                ('Time', models.TimeField(default=datetime.datetime.now, verbose_name='時間選択')),
                ('first_diameter', models.FloatField(default=0, verbose_name='刃先径')),
                ('used_count', models.IntegerField(default=0, verbose_name='使用数')),
            ],
        ),
    ]
